  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  jobs:
    test_script:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run ShellCheck
          uses: ludeeus/action-shellcheck@master
        - name: Test run lambda creation with python
          run: |
            export TMPDIR=$RUNNER_TEMP 
            bash create-layer.sh pandas-numpy-layer python3.9 numpy pandas
        - name: Test run lambda creation with node
          run: |
            export TMPDIR=$RUNNER_TEMP
            bash create-layer.sh request-moment-layer nodejs14.x request moment