  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  jobs:
    test_script:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run ShellCheck
          uses: ludeeus/action-shellcheck@master
        - name: Test run lambda creation with python
          run: |
            export TMPDIR=$RUNNER_TEMP
            bash create-layer.sh -n requests-layer -r python3.9 -m "requests pyyaml"
        - name: Test run lambda creation with node
          run: |
            export TMPDIR=$RUNNER_TEMP
            bash create-layer.sh -n request-moment-layer -r nodejs14.x -p "request moment"
